### ISSUE TITLE
UTF8 encoding

### ISSUE THREAD

**Issue by jisp7** [snakefoot/snaketail-net#101]
Looks like ANSI is only supported file encoding. Support for UTF8 would be perfect.

**Comment by snakefoot** [comment]
Not sure I understand, since you can change what encoding it will use for files.

It will automatically try to detect the encoding from the BOM, and if no BOM then it will default to ANSI.

You can change the default encoding for all files, by opening a file file and changing the encoding and then press "Save as default".

**Comment by jisp7** [comment]
I didn't notice the view option, thats what i need. I'll try this, thank you!
